# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    container_name: proyecto2DB
    image: postgres
    volumes:
      - my_pg_v:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=proyecto2
      - POSTGRES_PASSWORD=proyecto2
      - POSTGRES_DB=proyecto2
    ports:
      - 5432:5432
volumes:
  my_pg_v: